---
title: "timeseries_102022"
author: "julia"
date: "2022-10-21"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
```


```{r}
data <- read.csv("C:/Users/Julia/Documents/GitHub/tibetan-longevity/biog_main/cbdb_ddm_bdrc.csv")
head(data)
```

```{r}
df <- 
  filter(data, data=="bdrc") %>% 
  #post 1000
  filter(., ddate > 1000) %>%
  select(ddate) %>% 
  mutate(count = 1) %>% 
  group_by(ddate) %>% 
  summarise(count = n()) %>% 
  rename(year=ddate)
range(df$year)
```
```{r}
head(df)
```

```{r}
years <- 
  seq(range(df$year)[1], range(df$year)[2]) %>% 
  data.frame() %>% 
  rename(year=".")
```


```{r}
df2 <- left_join(years, df, by = c("year"="year"))%>%mutate_all(funs(replace_na(.,0)))
head(df2)
```


```{r}
ggplot(data=df2, aes(x=year, y=count, group=1)) +
  geom_line() +
  scale_x_continuous(breaks = seq(1000, 2000, 100), limits=c(1000,2000), name = "Year of Death", expand = c(0, 0)) +    ggtitle("Plot of number of reported deaths over time") 
```

```{r}
bdrc_ts <- ts(df2$count, frequency=1, start=1000)
bdrc_ts
```
```{r}
plot.ts(bdrc_ts)
```

```{r}
plot.ts(log(bdrc_ts))
```

```{r}
library("TTR")
```

```{r}
bdrc_ts_sma3 <- SMA(bdrc_ts, n=1)
plot.ts(bdrc_ts_sma3)
```

```{r}
age_of_deaths <- c(83, 67, 45, 28, 65, 23, 49, 46, 10, 21, 18, 57, 88)
age_of_deaths %>% head()
```

```{r}
age_of_deaths_ts <- ts(age_of_deaths)
age_of_deaths_ts
```

```{r}
plot.ts(age_of_deaths_ts)
```

```{r}
age_of_deaths_ts_SMA3 <- SMA(age_of_deaths_ts,n=3)
plot.ts(age_of_deaths_ts_SMA3)
```

```{r}
df4 <- df2  %>% mutate(decade = floor(year/10)*10) %>% 
      group_by(decade) %>% 
      summarize(sum=sum(count)) %>% 
      mutate(pct = sum/2314)


ggplot(data=df4, aes(x=decade, y=pct, group=1)) +
  geom_line()
```

