---
title: "cbdb_analysis"
author: "Julia Ulziisaikhan"
date: "2/11/2022"
output: html_document
---

```{r, warning=F, error=F}
library(tidyverse)
library(ggplot2)
library(sqldf)
library(RSQLite)
library(lubridate)
library(gt)
library(scales)
library(egg)
setwd("C:/Users/ulzii/OneDrive/Documents/spring22/tuttle/")
```

'df' contains data from `ddm`,`cbdb`,`bdrc`
```{r}
df <- read.csv("C:/Users/ulzii/OneDrive/Documents/spring22/tuttle/biog_main/cbdb_ddm_bdrc.csv")
unique(df$data)
```

Lifespan means by data
```{r}
mu <- plyr::ddply(df, "data", summarise, grp.mean=mean(lifespan))
mu
```


```{r}
ggplot(df, aes(x=lifespan, fill=data)) +
  geom_density(alpha=0.4) +
  scale_x_continuous(breaks = seq(0, 110, 10), limits=c(0,110), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0.01, 0.04, 0.01), limits=c(0,0.03), expand = c(0, 0)) +
  theme_bw()+facet_grid(data ~ .) +
  geom_vline(data=mu, aes(xintercept=grp.mean, color="Mean"),
             linetype=1)+
  labs(title="Lifespan density curve, by data source",x="Lifespan in Years", y = "Density") +
  theme(plot.title = element_text(hjust = 0.5),plot.background = element_rect(fill = "grey90"))
```

# Summary tables by historical period

```{r}
# periodization
per <- read.csv("C:/Users/ulzii/OneDrive/Documents/Fall 2021/R files/longevity_data - Major Temporal Divisions.csv")
per$period <- per$period %>% str_to_title()

#Creating Tables
per_t <- per %>% filter(is.na(sub_period), periodization=="historical_tibet")
bdrc_per <- sqldf("select * from bdrc
                left join per_t
                on bdrc.ddate between per_t.start and per_t.end")

summ_t_per <-
  group_by(bdrc_per, period) %>% dplyr::summarise(mean=round(mean(lifespan)), sd=round(sd(lifespan)),n=n()) %>% arrange(desc(n))

x <- c("Imperial Period", "Dark Ages", "Renaissance/Local Hegemony", "Sakya/Kagyu Hegemony", "Gelukpa/Ganden Hegemony", "Chinese Hegemony") %>% rev()

summ_t_per %>%
  mutate(period =  factor(period, levels = x)) %>%
  arrange(period)  %>% tidyr::drop_na() 
```

```{r}
base_cbdb <- 
  ggplot(data=df %>% filter(data=="cbdb"), aes(x=ddate, y=lifespan)) + 
  geom_point(alpha=0.1, color="#00BA38") +
  labs(title="Longevity Over Time") +
  scale_x_continuous(breaks = seq(1000, 2022, 100), limits=c(1000,2022), name = "Year of Death", expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(10, 100, 10), limits=c(0,100), name = "Lifespan (Years)", expand = c(0, 0)) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        plot.background = element_rect(fill = "grey90"),
        axis.text.x = element_text(size=9, angle=30, vjust = 1.25, hjust=1.1),
        axis.line = element_line(colour = "black", size = 0.3, linetype = "solid"),
        panel.background = element_rect(fill = "white", color='black'),
        panel.grid.major = element_line(color = 'grey85', size=0.5),
        panel.grid.minor = element_line(color = 'grey85', size=0.5)) +
  annotate("text", x = .5*(960+1270), y = 15, label = "Song Dynasty") +
  annotate("text", x = .5*(1271+1368), y = 15, label = "Yuan") +
  annotate("text", x = .5*(1369+1644), y = 15, label = "Ming") +
  annotate("text", x = .5*(1645+1912), y = 15, label = "Qing") +
  annotate("text", x = 1965, y = 15, label = "Modern\nPeriod") +
  geom_vline(xintercept = c(960,1271,1369, 1645, 1913))

base_cbdb
```


```{r}
cbdb_loess <- base_cbdb + geom_smooth(method="loess", color="darkgreen", fullrange=TRUE)

cbdb_loess
```

```{r}
bdrc <- df %>% filter(data=="bdrc")
per_t <- per %>% filter(is.na(sub_period), periodization=="historical_tibet")
bdrc_per <- sqldf("select * from bdrc
                left join per_t
                on bdrc.ddate between per_t.start and per_t.end")

x <- c("Imperial Period", "Dark Ages", "Renaissance/Local Hegemony", "Sakya/Kagyu Hegemony", "Gelukpa/Ganden Hegemony", "Chinese Hegemony") %>% rev()
summ_t_per <-
  group_by(bdrc_per, period) %>% 
  dplyr::summarise(mean=round(mean(lifespan)), sd=round(sd(lifespan)),n=n()) %>%
  arrange(desc(n)) %>%
  mutate(period =  factor(period, levels = x)) %>%
  arrange(period)  %>% 
  tidyr::drop_na()

summ_t_per

```


```{r}
per_c <- per %>% filter(is.na(sub_period), periodization=="historical_china")
cbdb <- df %>% filter(data=="cbdb")
cbdb_per <- sqldf("select * from cbdb
                left join per_c
                on cbdb.ddate between per_c.start and per_c.end")
x_c <- c("Song Dynasty", "Yuan Dynasty", "Ming Dynasty", "Qing Dynasty",
       "Modern Period") %>% rev()

summ_c1_per <-
  group_by(cbdb_per, period) %>% 
  dplyr::summarise(mean=round(mean(lifespan)), n=n(), sd=round(sd(lifespan))) %>%
  arrange(desc(n)) %>%
  mutate(period =  factor(period, levels = x_c)) %>%
  arrange(period)  %>% tidyr::drop_na() 

summ_c1_per %>% map_df(rev)
```


```{r}
ddm <- df %>% filter(data=="ddm")
ddm_per <- sqldf("select * from ddm
                left join per_c
                on ddm.ddate between per_c.start and per_c.end")
summ_c2_per <-
  group_by(ddm_per, period) %>% 
  dplyr::summarise(mean=round(mean(lifespan)), n=n(), sd=round(sd(lifespan))) %>%
  arrange(desc(n)) %>%
  mutate(period =  factor(period, levels = x_c)) %>%
  arrange(period)  %>% tidyr::drop_na() 

summ_c2_per
```

```{r}
summ_c_per <-
  group_by(ddm_per, period) %>% dplyr::summarise(mean=round(mean(lifespan)), n=n(), sd=round(sd(lifespan))) %>% arrange(desc(n))

summ_c_per

x_c <- c("Song Dynasty", "Yuan Dynasty", "Ming Dynasty", "Qing Dynasty",
       "Modern Period") %>% rev()
```


```{r}
set.seed(100)
df_even <- 
  df %>%
  group_by(data) %>%
  sample_n(2327)

df_china <- 
  df %>%
  filter(data!="bdrc") %>%
  group_by(data) %>%
  sample_n(5981)

df_china  %>% group_by(data) %>% summarise(n=n()) # stratify sampling
df_even %>% group_by(data) %>% summarise(n=n()) # stratify sampling
```

```{r}
colors <- rev(c("steelblue4", "#00BA38", "orangered2"))
ggplot(data=df_even, aes(x=ddate, y=lifespan, colour=data, fill=data)) + 
  geom_point(alpha=0.1) +
  geom_smooth(method="lm", fullrange=TRUE) +
  labs(title="Longevity Over Time") +
  scale_x_continuous(breaks = seq(500, 2022, 100), limits=c(500,2022), name = "Year of Death", expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(10, 100, 10), limits=c(0,100), name = "Lifespan (Years)", expand = c(0, 0)) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        plot.background = element_rect(fill = "grey90"),
        axis.text.x = element_text(size=9, angle=30, vjust = 1.25, hjust=1.1),
        axis.line = element_line(colour = "black", size = 0.3, linetype = "solid"),
        panel.background = element_rect(fill = "white", color='black'),
        panel.grid.major = element_line(color = 'grey85', size=0.5),
        panel.grid.minor = element_line(color = 'grey85', size=0.5)
        ,        legend.position="bottom"
        )+
  scale_fill_manual(values=colors)+
  scale_color_manual(values=colors)
```


```{r}
ggplot(data=df_china, aes(x=ddate, y=lifespan, colour=data, fill=data)) + 
  geom_point(alpha=0.12) +
  geom_smooth(method="loess", fullrange=TRUE) +
  labs(title="Longevity Over Time") +
  scale_x_continuous(breaks = seq(500, 2022, 100), limits=c(500,2022), name = "Year of Death", expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(10, 100, 10), limits=c(0,100), name = "Lifespan (Years)", expand = c(0, 0)) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5),
        plot.background = element_rect(fill = "grey90"),
        axis.text.x = element_text(size=9, angle=30, vjust = 1.25, hjust=1.1),
        axis.line = element_line(colour = "black", size = 0.3, linetype = "solid"),
        panel.background = element_rect(fill = "white", color='black'),
        panel.grid.major = element_line(color = 'grey85', size=0.5),
        panel.grid.minor = element_line(color = 'grey85', size=0.5)
        ,        legend.position="bottom"
        )+
  scale_fill_manual(values=colors[-1])+
  scale_color_manual(values=colors[-1])+
  annotate("text", x = .5*(960+1270), y = 15, label = "Song Dynasty") +
  annotate("text", x = .5*(1271+1368), y = 15, label = "Yuan") +
  annotate("text", x = .5*(1369+1644), y = 15, label = "Ming") +
  annotate("text", x = .5*(1645+1912), y = 15, label = "Qing") +
  annotate("text", x = 1965, y = 15, label = "Modern\nPeriod") +
  geom_vline(xintercept = c(960,1271,1369, 1645, 1913))
```

